apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindmate-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindmate-backend
  template:
    metadata:
      labels:
        app: mindmate-backend
    spec:
      containers:
        - name: backend
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401069/mindmate-backend:IMAGE_TAG
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: mindmate-backend-env
