apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindmate-fe
  namespace: "2401055"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindmate-fe
  template:
    metadata:
      labels:
        app: mindmate-fe
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: frontend
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401055/mindmate-fe:{{TAG}}
          ports:
            - containerPort: 80
