apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindmate-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindmate-frontend
  template:
    metadata:
      labels:
        app: mindmate-frontend
    spec:
      containers:
      - name: frontend
        image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401069/mindmate-frontend:IMAGE_TAG
        ports:
        - containerPort: 80
