apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mindmate-ingress
spec:
  rules:
    - host: 2401069.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mindmate-frontend
                port:
                  number: 80
