apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mindmate-ingress-v2
  namespace: "2401055"
spec:
  rules:
    - host: mindmate.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mindmate-fe
                port:
                  number: 80

    - host: mindmate-api.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mindmate-be
                port:
                  number: 80
