name: Deploy to WSL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    # -------- TAILSCALE ----------
    - name: Connect to Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
        oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
        tags: tag:ci

    # -------- FRONTEND ----------
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install frontend dependencies
      working-directory: MindMate-FE
      run: npm install

    - name: Build frontend
      working-directory: MindMate-FE
      run: npm run build

    - name: Copy frontend build to WSL
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "MindMate-FE/dist/*"
        target: "/home/hp/apps/mindmate-frontend/"

    # -------- BACKEND ----------
    - name: Copy backend files properly
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: |
          MindMate-BE/app/*
          MindMate-BE/requirements.txt
        target: "/home/hp/apps/mindmate-backend/"

    - name: Install deps & restart FastAPI
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/hp/apps/mindmate-backend
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart mindmate-backend
